apiVersion: {{ .Values.rbacApiVersion }}/v1
kind: ClusterRole
metadata:
  name: system:controller:operators-lifecycle-manager
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: olm-operators-serviceaccount
  namespace: {{ .Values.namespace }}
---
apiVersion: {{ .Values.rbacApiVersion }}/v1
kind: ClusterRoleBinding
metadata:
  name: olm-operators-binding-{{ .Values.namespace }}
roleRef:
  apiGroup: {{ .Values.rbacApiVersion }}
  kind: ClusterRole
  name: system:controller:operators-lifecycle-manager
subjects:
- kind: ServiceAccount
  name: olm-operators-serviceaccount
  namespace: {{ .Values.namespace }}
